name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "24"
          cache: maven

      - name: Run tests
        run: mvn -B -U test

      - name: Upload surefire reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports/**
          if-no-files-found: ignore

      - name: Upload screenshots & page source (if any)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: |
            target/artifacts/screenshots/**
            target/artifacts/pagesource/**
          if-no-files-found: ignore
